# 指定基于的基础镜像
FROM ubuntu:latest
# 维护者信息
MAINTAINER transfer <448217518@qq.com>

# 更新源
RUN apt-get update

# 安装python3
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip
